export { default as Landing}  from "./Landing"
export {default as Cryptoccurrencies} from "./Cryptoccurrencies"
export { default as Exchanges} from "./Exchanges"
export { default as News} from "./News"
export { default as Live} from "./Live"